version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=infrastructuredbtests
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
